+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Tue Aug  8 03:51:48 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL anaconda-core
+ pkgs=anaconda-core
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs anaconda-core --node 1 --tempfile ''
Tue Aug  8 03:51:54 2023 - INFO  - pkgs:(anaconda-core) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ sed -i s/MAX_RAM_ON=2097152/MAX_RAM_ON=4097152/g /usr/libexec/anaconda/zramswapon
sed: can't read /usr/libexec/anaconda/zramswapon: No such file or directory
+ systemctl start zram.service
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue Aug  8 03:51:54 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Tue Aug  8 03:51:55 2023 - INFO  - Start testing...
+ test_execution zram.service
+ service=zram.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-08-08 03:51:55'
+ test_restart zram.service
+ service=zram.service
+ systemctl restart zram.service
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 127 0 0 'zram.service restart failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='zram.service restart failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'zram.service restart failed'
+ LOG_ERROR 'zram.service restart failed'
+ message='zram.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'zram.service restart failed'
Tue Aug  8 03:51:55 2023 - ERROR - zram.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Tue Aug  8 03:51:56 2023 - ERROR - ../common/common_lib.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status zram.service
+ grep 'Active: active'
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 1 0 0 'zram.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='zram.service restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'zram.service restart failed'
+ LOG_ERROR 'zram.service restart failed'
+ message='zram.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'zram.service restart failed'
Tue Aug  8 03:52:02 2023 - ERROR - zram.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Tue Aug  8 03:52:03 2023 - ERROR - ../common/common_lib.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl stop zram.service
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 127 0 0 'zram.service stop failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='zram.service stop failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'zram.service stop failed'
+ LOG_ERROR 'zram.service stop failed'
+ message='zram.service stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'zram.service stop failed'
Tue Aug  8 03:52:03 2023 - ERROR - zram.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 39'
+ message='../common/common_lib.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 39'
Tue Aug  8 03:52:04 2023 - ERROR - ../common/common_lib.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status zram.service
+ grep 'Active: inactive'
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 1 0 0 'zram.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='zram.service stop failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'zram.service stop failed'
+ LOG_ERROR 'zram.service stop failed'
+ message='zram.service stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'zram.service stop failed'
Tue Aug  8 03:52:10 2023 - ERROR - zram.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Tue Aug  8 03:52:11 2023 - ERROR - ../common/common_lib.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start zram.service
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 127 0 0 'zram.service start failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='zram.service start failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'zram.service start failed'
+ LOG_ERROR 'zram.service start failed'
+ message='zram.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'zram.service start failed'
Tue Aug  8 03:52:11 2023 - ERROR - zram.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Tue Aug  8 03:52:12 2023 - ERROR - ../common/common_lib.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status zram.service
+ grep 'Active: active'
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 1 0 0 'zram.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='zram.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'zram.service start failed'
+ LOG_ERROR 'zram.service start failed'
+ message='zram.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'zram.service start failed'
Tue Aug  8 03:52:18 2023 - ERROR - zram.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Tue Aug  8 03:52:19 2023 - ERROR - ../common/common_lib.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ test_enabled zram.service
+ service=zram.service
++ systemctl is-enabled zram.service
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ state=
+ '[' '' == enabled ']'
+ '[' '' == disabled ']'
+ '[' '' == masked ']'
+ '[' '' == static ']'
+ LOG_INFO 'Unit is indirect, ignoring.'
+ message='Unit is indirect, ignoring.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Unit is indirect, ignoring.'
Tue Aug  8 03:52:19 2023 - INFO  - Unit is indirect, ignoring.
+ journalctl --since '2023-08-08 03:51:55' -u zram.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ CHECK_RESULT 1 0 1 'There is an error message for the log of zram.service'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of zram.service'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ test_reload zram.service
+ service=zram.service
+ systemctl start zram.service
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ systemctl reload zram.service
+ grep 'Job type reload is not applicable'
+ CHECK_RESULT 1 0 0 'Job type reload is not applicable for unit zram.service'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit zram.service'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Job type reload is not applicable for unit zram.service'
+ LOG_ERROR 'Job type reload is not applicable for unit zram.service'
+ message='Job type reload is not applicable for unit zram.service'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Job type reload is not applicable for unit zram.service'
Tue Aug  8 03:52:20 2023 - ERROR - Job type reload is not applicable for unit zram.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 91'
+ message='../common/common_lib.sh line 91'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 91'
Tue Aug  8 03:52:21 2023 - ERROR - ../common/common_lib.sh line 91
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl status zram.service
+ grep 'Active: active'
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ systemctl status zram.service
+ grep 'inactive (dead)'
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ return 1
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Tue Aug  8 03:52:21 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Aug  8 03:52:22 2023 - ERROR - failed to execute the case.
+ exit 7
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Tue Aug  8 03:52:22 2023 - INFO  - start environment cleanup.
+ sed -i s/MAX_RAM_ON=4097152/MAX_RAM_ON=2097152/g /usr/libexec/anaconda/zramswapon
sed: can't read /usr/libexec/anaconda/zramswapon: No such file or directory
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Tue Aug  8 03:52:23 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Tue Aug  8 03:52:23 2023 - INFO  - Finish environment cleanup!
