+ source ../common/storage_disk_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Tue Sep  5 01:31:15 2023 - INFO  - Start environment preparation.
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks='sr0 vdb vdc vdd vde'
+ disk_list=($disks)
+ local_disk=sr0
+ local_disk1=vdb
+ local_disk2=vdc
+ local_disk3=vdd
+ pvcreate -y /dev/vdb /dev/sr0
oe_test_storage_lvm_split_VG.sh: line 23: pvcreate: command not found
+ vgcreate openeulertest /dev/vdb
oe_test_storage_lvm_split_VG.sh: line 24: vgcreate: command not found
+ lvcreate -L 50MB -n test openeulertest -y
oe_test_storage_lvm_split_VG.sh: line 25: lvcreate: command not found
+ LOG_INFO 'Environmental preparation is over.'
+ message='Environmental preparation is over.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Environmental preparation is over.'
Tue Sep  5 01:31:16 2023 - INFO  - Environmental preparation is over.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Tue Sep  5 01:31:16 2023 - INFO  - Start executing testcase!
+ pvscan
oe_test_storage_lvm_split_VG.sh: line 31: pvscan: command not found
+ grep /dev/vdb
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 32'
+ message='oe_test_storage_lvm_split_VG.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 32'
Tue Sep  5 01:31:16 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ vgextend openeulertest /dev/sr0 -y
oe_test_storage_lvm_split_VG.sh: line 33: vgextend: command not found
+ pvdisplay
+ grep sr0
oe_test_storage_lvm_split_VG.sh: line 34: pvdisplay: command not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 35'
+ message='oe_test_storage_lvm_split_VG.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 35'
Tue Sep  5 01:31:16 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ pvmove /dev/vdb /dev/sr0
oe_test_storage_lvm_split_VG.sh: line 36: pvmove: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 37'
+ message='oe_test_storage_lvm_split_VG.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 37'
Tue Sep  5 01:31:16 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ grep /dev/sr0
+ pvscan
+ grep openeulertest
oe_test_storage_lvm_split_VG.sh: line 38: pvscan: command not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 39'
+ message='oe_test_storage_lvm_split_VG.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 39'
Tue Sep  5 01:31:16 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ lvchange -a n /dev/openeulertest/test
oe_test_storage_lvm_split_VG.sh: line 40: lvchange: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 41'
+ message='oe_test_storage_lvm_split_VG.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 41'
Tue Sep  5 01:31:16 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ vgsplit openeulertest openeulertest1 /dev/vdb
oe_test_storage_lvm_split_VG.sh: line 42: vgsplit: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 43'
+ message='oe_test_storage_lvm_split_VG.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 43'
Tue Sep  5 01:31:16 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ vgdisplay
oe_test_storage_lvm_split_VG.sh: line 44: vgdisplay: command not found
+ grep openeulertest1
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 45'
+ message='oe_test_storage_lvm_split_VG.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 45'
Tue Sep  5 01:31:16 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ lvcreate -y -L 1G -n openeuler1 openeulertest1
oe_test_storage_lvm_split_VG.sh: line 46: lvcreate: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 47'
+ message='oe_test_storage_lvm_split_VG.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 47'
Tue Sep  5 01:31:16 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ mkfs.ext4 /dev/openeulertest1/openeuler1
mke2fs 1.47.0 (5-Feb-2023)
The file /dev/openeulertest1/openeuler1 does not exist and no size was specified.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 49'
+ message='oe_test_storage_lvm_split_VG.sh line 49'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 49'
Tue Sep  5 01:31:16 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 49
+ '[' 0 -eq 1 ']'
+ return 0
+ mount /dev/openeulertest1/openeuler1 /mnt
mount: /mnt: special device /dev/openeulertest1/openeuler1 does not exist.
       dmesg(1) may have more information after failed mount system call.
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 51'
+ message='oe_test_storage_lvm_split_VG.sh line 51'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 51'
Tue Sep  5 01:31:16 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 51
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of testcase execution!'
+ message='End of testcase execution!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution!'
Tue Sep  5 01:31:16 2023 - INFO  - End of testcase execution!
+ CASE_RESULT 0
+ case_re=0
+ test -z 10
+ test 10 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Sep  5 01:31:16 2023 - ERROR - failed to execute the case.
+ exit 10
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Tue Sep  5 01:31:16 2023 - INFO  - start environment cleanup.
+ umount /dev/openeulertest1/openeuler1
umount: /dev/openeulertest1/openeuler1: no mount point specified.
+ lvremove -y openeulertest/test openeulertest1/openeuler1
oe_test_storage_lvm_split_VG.sh: line 58: lvremove: command not found
+ vgremove -y openeulertest openeulertest1
oe_test_storage_lvm_split_VG.sh: line 59: vgremove: command not found
+ pvremove /dev/vdb /dev/sr0
oe_test_storage_lvm_split_VG.sh: line 60: pvremove: command not found
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Tue Sep  5 01:31:16 2023 - INFO  - Finish environment cleanup.
