+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n function ']'
+ config_params
+ LOG_INFO 'Start parameters preparation.'
+ message='Start parameters preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start parameters preparation.'
Tue Aug 22 13:17:00 2023 - INFO  - Start parameters preparation.
+ point_list=($(CREATE_FS))
++ CREATE_FS
++ fs_type='ext3 ext4 xfs'
+++ date +%Y%m%d%H%M%S
++ cur_date=20230822131700
+++ CREATE_VG
++++ date +%Y%m%d%H%M%S
+++ cur_date=20230822131700
++++ lsblk
++++ grep disk
++++ awk '{print $1}'
++++ tail -n 1
+++ free_disk=vdb
+++ disk_name=/dev/vdb
+++ pvcreate /dev/vdb -f
+++ [[ 127 -eq 0 ]]
++++ pvcreate /dev/vdb
++++ grep test_vggroup
++++ cut -d '"' -f 4
+++ vggroup=
+++ printf
printf: usage: printf [-v var] format [arguments]
++ vggroup=
++ count=1
++ msg=' '
++ for fs in ${fs_type[@]}
++ lvname=test_lv120230822131700
++ point=/tmp/point120230822131700
++ lvcreate -n test_lv120230822131700 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext3 /dev//test_lv120230822131700
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv120230822131700 does not exist and no size was specified.
++ mkdir /tmp/point120230822131700
++ mount /dev//test_lv120230822131700 /tmp/point120230822131700
mount: /tmp/point120230822131700: special device /dev//test_lv120230822131700 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230822131700 '
++ count=2
++ for fs in ${fs_type[@]}
++ lvname=test_lv220230822131700
++ point=/tmp/point220230822131700
++ lvcreate -n test_lv220230822131700 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext4 /dev//test_lv220230822131700
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv220230822131700 does not exist and no size was specified.
++ mkdir /tmp/point220230822131700
++ mount /dev//test_lv220230822131700 /tmp/point220230822131700
mount: /tmp/point220230822131700: special device /dev//test_lv220230822131700 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230822131700 /tmp/point220230822131700 '
++ count=3
++ for fs in ${fs_type[@]}
++ lvname=test_lv320230822131700
++ point=/tmp/point320230822131700
++ lvcreate -n test_lv320230822131700 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t xfs /dev//test_lv320230822131700
mkfs: failed to execute mkfs.xfs: No such file or directory
++ mkdir /tmp/point320230822131700
++ mount /dev//test_lv320230822131700 /tmp/point320230822131700
mount: /tmp/point320230822131700: special device /dev//test_lv320230822131700 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230822131700 /tmp/point220230822131700 /tmp/point320230822131700 '
++ count=4
++ echo /tmp/point120230822131700 /tmp/point220230822131700 /tmp/point320230822131700
+ ext3_point=/tmp/point220230822131700
+ ext4_point=/tmp/point320230822131700
+ xfs_point=
+ echo 'test ext3'
+ mkdir -p /tmp/point220230822131700/testDir/test1
+ LOG_INFO 'End of parameters preparation!'
+ message='End of parameters preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of parameters preparation!'
Tue Aug 22 13:17:00 2023 - INFO  - End of parameters preparation!
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Aug 22 13:17:00 2023 - INFO  - Start to run test.
+ ln -s /tmp/point220230822131700/testFile /tmp/point320230822131700/testSoft1
+ ln -s /tmp/point220230822131700/testDir /tmp/point320230822131700/testSoft2
+ grep ext3 /tmp/point320230822131700/testSoft1
test ext3
+ CHECK_RESULT 0 0 0 'The sort link file on ext4 has some errors.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The sort link file on ext4 has some errors.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ls /tmp/point320230822131700/testSoft2
+ grep test1
test1
+ CHECK_RESULT 0 0 0 'The sort link directory on ext4 has some errors.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The sort link directory on ext4 has some errors.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ln -s /tmp/point220230822131700/testFile /testSoft3
+ ln -s /tmp/point220230822131700/testDir /testSoft4
+ grep ext3 /testSoft3
test ext3
+ CHECK_RESULT 0 0 0 'The sort link file on xfs has some errors.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The sort link file on xfs has some errors.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ls /testSoft4
+ grep test1
test1
+ CHECK_RESULT 0 0 0 'The sort link directory on xfs has some errors.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The sort link directory on xfs has some errors.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Aug 22 13:17:00 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Tue Aug 22 13:17:00 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Aug 22 13:17:00 2023 - INFO  - Start to restore the test environment.
++ echo /tmp/point120230822131700 /tmp/point220230822131700 /tmp/point320230822131700
+ list='/tmp/point120230822131700 /tmp/point220230822131700 /tmp/point320230822131700'
+ REMOVE_FS '/tmp/point120230822131700 /tmp/point220230822131700 /tmp/point320230822131700'
+ point_list=($1)
++ seq 0 2
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point120230822131700
++ df -T
++ grep /tmp/point120230822131700
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point220230822131700
++ df -T
++ grep /tmp/point220230822131700
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point320230822131700
++ df -T
++ grep /tmp/point320230822131700
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Aug 22 13:17:00 2023 - INFO  - End to restore the test environment.
