+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Aug  8 01:03:57 2023 - INFO  - Start to run test.
+ test_execution runlevel4.target
+ service=runlevel4.target
++ date '+%Y-%m-%d %T'
+ log_time='2023-08-08 01:03:57'
+ test_restart runlevel4.target
+ service=runlevel4.target
+ systemctl restart runlevel4.target
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 127 0 0 'runlevel4.target restart failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='runlevel4.target restart failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'runlevel4.target restart failed'
+ LOG_ERROR 'runlevel4.target restart failed'
+ message='runlevel4.target restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'runlevel4.target restart failed'
Tue Aug  8 01:03:58 2023 - ERROR - runlevel4.target restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Tue Aug  8 01:03:58 2023 - ERROR - ../common/common_lib.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status runlevel4.target
+ grep 'Active: active'
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 1 0 0 'runlevel4.target restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='runlevel4.target restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'runlevel4.target restart failed'
+ LOG_ERROR 'runlevel4.target restart failed'
+ message='runlevel4.target restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'runlevel4.target restart failed'
Tue Aug  8 01:04:04 2023 - ERROR - runlevel4.target restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Tue Aug  8 01:04:05 2023 - ERROR - ../common/common_lib.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl stop runlevel4.target
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 127 0 0 'runlevel4.target stop failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='runlevel4.target stop failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'runlevel4.target stop failed'
+ LOG_ERROR 'runlevel4.target stop failed'
+ message='runlevel4.target stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'runlevel4.target stop failed'
Tue Aug  8 01:04:05 2023 - ERROR - runlevel4.target stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 39'
+ message='../common/common_lib.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 39'
Tue Aug  8 01:04:06 2023 - ERROR - ../common/common_lib.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status runlevel4.target
+ grep 'Active: inactive'
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 1 0 0 'runlevel4.target stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='runlevel4.target stop failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'runlevel4.target stop failed'
+ LOG_ERROR 'runlevel4.target stop failed'
+ message='runlevel4.target stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'runlevel4.target stop failed'
Tue Aug  8 01:04:12 2023 - ERROR - runlevel4.target stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Tue Aug  8 01:04:12 2023 - ERROR - ../common/common_lib.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start runlevel4.target
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 127 0 0 'runlevel4.target start failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='runlevel4.target start failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'runlevel4.target start failed'
+ LOG_ERROR 'runlevel4.target start failed'
+ message='runlevel4.target start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'runlevel4.target start failed'
Tue Aug  8 01:04:13 2023 - ERROR - runlevel4.target start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Tue Aug  8 01:04:13 2023 - ERROR - ../common/common_lib.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status runlevel4.target
+ grep 'Active: active'
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 1 0 0 'runlevel4.target start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='runlevel4.target start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'runlevel4.target start failed'
+ LOG_ERROR 'runlevel4.target start failed'
+ message='runlevel4.target start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'runlevel4.target start failed'
Tue Aug  8 01:04:20 2023 - ERROR - runlevel4.target start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Tue Aug  8 01:04:20 2023 - ERROR - ../common/common_lib.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ test_enabled runlevel4.target
+ service=runlevel4.target
++ systemctl is-enabled runlevel4.target
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ state=
+ '[' '' == enabled ']'
+ '[' '' == disabled ']'
+ '[' '' == masked ']'
+ '[' '' == static ']'
+ LOG_INFO 'Unit is indirect, ignoring.'
+ message='Unit is indirect, ignoring.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Unit is indirect, ignoring.'
Tue Aug  8 01:04:21 2023 - INFO  - Unit is indirect, ignoring.
+ journalctl --since '2023-08-08 01:03:57' -u runlevel4.target
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ CHECK_RESULT 1 0 1 'There is an error message for the log of runlevel4.target'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of runlevel4.target'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ test_reload runlevel4.target
+ service=runlevel4.target
+ systemctl start runlevel4.target
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ grep 'Job type reload is not applicable'
+ systemctl reload runlevel4.target
+ CHECK_RESULT 1 0 0 'Job type reload is not applicable for unit runlevel4.target'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit runlevel4.target'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Job type reload is not applicable for unit runlevel4.target'
+ LOG_ERROR 'Job type reload is not applicable for unit runlevel4.target'
+ message='Job type reload is not applicable for unit runlevel4.target'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Job type reload is not applicable for unit runlevel4.target'
Tue Aug  8 01:04:21 2023 - ERROR - Job type reload is not applicable for unit runlevel4.target
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 91'
+ message='../common/common_lib.sh line 91'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 91'
Tue Aug  8 01:04:22 2023 - ERROR - ../common/common_lib.sh line 91
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl status runlevel4.target
+ grep 'Active: active'
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ systemctl status runlevel4.target
+ grep 'inactive (dead)'
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ return 1
+ LOG_INFO 'End of the test.'
+ message='End of the test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of the test.'
Tue Aug  8 01:04:23 2023 - INFO  - End of the test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Aug  8 01:04:23 2023 - ERROR - failed to execute the case.
+ exit 7
+ POST_TEST_DEFAULT
+ LOG_INFO 'oe_test_target_runlevel4.sh post_test'
+ message='oe_test_target_runlevel4.sh post_test'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'oe_test_target_runlevel4.sh post_test'
Tue Aug  8 01:04:24 2023 - INFO  - oe_test_target_runlevel4.sh post_test
