+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Fri Sep  1 02:23:00 2023 - INFO  - Start environment preparation.
+ DNF_INSTALL 'net-tools NetworkManager ethtool'
+ pkgs='net-tools NetworkManager ethtool'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'net-tools NetworkManager ethtool' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpg2yngkjs
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpg2yngkjs
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Fri Sep  1 02:23:30 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Fri Sep  1 02:23:30 2023 - INFO  - Start testing...
+ systemctl restart NetworkManager
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl status NetworkManager
+ grep 'Active: active'
     Active: active (running) since Fri 2023-09-01 02:23:32 CST; 431ms ago
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ df -h /
+ grep overlay
+ nmcli connection show
+ grep ''
NAME                UUID                                  TYPE      DEVICE 
lo                  10b8dc5a-6691-4986-a684-69cc4ad4a2d5  loopback  lo     
Wired connection 1  f5097adc-5562-3d0f-a4b4-e14201b0ed33  ethernet  enp0s3 
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ip link
+ grep ''
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 52:54:00:11:45:01 brd ff:ff:ff:ff:ff:ff
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ route
+ grep default
default         _gateway        0.0.0.0         UG    100    0        0 enp0s3
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ethtool ''
netlink error: no device matches name (offset 24)
netlink error: No such device
netlink error: no device matches name (offset 24)
netlink error: No such device
netlink error: no device matches name (offset 24)
netlink error: No such device
netlink error: no device matches name (offset 24)
netlink error: No such device
netlink error: no device matches name (offset 24)
netlink error: No such device
netlink error: no device matches name (offset 24)
netlink error: No such device
netlink error: no device matches name (offset 24)
netlink error: No such device
No data available
+ CHECK_RESULT 75
+ actual_result=75
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 75 ']'
+ '[' 0 -eq 0 ']'
+ test 75x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_network_001.sh line 47'
+ message='oe_test_network_001.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_network_001.sh line 47'
Fri Sep  1 02:23:34 2023 - ERROR - oe_test_network_001.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ ifconfig
+ grep ''
enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::43f1:d187:86e8:b082  prefixlen 64  scopeid 0x20<link>
        inet6 fec0::2045:dc12:aeff:fd74  prefixlen 64  scopeid 0x40<site>
        ether 52:54:00:11:45:01  txqueuelen 1000  (Ethernet)
        RX packets 77326  bytes 111656025 (106.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5422  bytes 359681 (351.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 2473  bytes 2937749 (2.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2473  bytes 2937749 (2.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ip a show ''
+ grep 192.1.1.11
Device "" does not exist.
+ ip addr add 192.1.1.11 dev ''
Cannot find device ""
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_network_001.sh line 52'
+ message='oe_test_network_001.sh line 52'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_network_001.sh line 52'
Fri Sep  1 02:23:35 2023 - ERROR - oe_test_network_001.sh line 52
+ '[' 0 -eq 1 ']'
+ return 0
+ ip a show ''
+ grep 192.1.1.11
Device "" does not exist.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_network_001.sh line 54'
+ message='oe_test_network_001.sh line 54'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_network_001.sh line 54'
Fri Sep  1 02:23:36 2023 - ERROR - oe_test_network_001.sh line 54
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Fri Sep  1 02:23:36 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Sep  1 02:23:37 2023 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Fri Sep  1 02:23:37 2023 - INFO  - start environment cleanup.
+ ip addr del 192.1.1.11 dev ''
Warning: Executing wildcard deletion to stay compatible with old scripts.
         Explicitly specify the prefix length (192.1.1.11/32) to avoid this warning.
         This special behaviour is likely to disappear in further releases,
         fix your scripts!
Cannot find device ""
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpg2yngkjs ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpg2yngkjs
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Fri Sep  1 02:23:46 2023 - INFO  - Finish environment cleanup!
