+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Wed Aug  9 02:22:31 2023 - INFO  - Start to prepare the database config.
++ date +%Y%m%d%H%M%S
+ cur_date=20230809022231
++ CREATE_VG
+++ date +%Y%m%d%H%M%S
++ cur_date=20230809022231
+++ lsblk
+++ grep disk
+++ awk '{print $1}'
+++ tail -n 1
++ free_disk=vdb
++ disk_name=/dev/vdb
++ pvcreate /dev/vdb -f
++ [[ 5 -eq 0 ]]
+++ pvcreate /dev/vdb
+++ grep test_vggroup
+++ cut -d '"' -f 4
++ vggroup=test_vggroup20230809021908
++ printf test_vggroup20230809021908
+ vggroup=test_vggroup20230809021908
+ lv1=test_lv120230809022231
+ lv2=test_lv220230809022231
+ lv3=test_lv320230809022231
+ lvcreate -n test_lv120230809022231 -L 2G test_vggroup20230809021908 -y
+ lvcreate -n test_lv220230809022231 -L 2G test_vggroup20230809021908 -y
+ lvcreate -n test_lv320230809022231 -L 2G test_vggroup20230809021908 -y
+ mkfs.ext3 /dev/test_vggroup20230809021908/test_lv120230809022231
mke2fs 1.47.0 (5-Feb-2023)
Discarding device blocks:      0/524288             done                            
Creating filesystem with 524288 4k blocks and 131072 inodes
Filesystem UUID: d9518925-dfcf-4b42-b294-881f59bd504f
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912

Allocating group tables:  0/16     done                            
Writing inode tables:  0/16     done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information:  0/16     done

+ mkfs.ext4 /dev/test_vggroup20230809021908/test_lv220230809022231
mke2fs 1.47.0 (5-Feb-2023)
Discarding device blocks:      0/524288             done                            
Creating filesystem with 524288 4k blocks and 131072 inodes
Filesystem UUID: f7d76991-c54d-49c1-9c06-03f2755687d3
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912

Allocating group tables:  0/16     done                            
Writing inode tables:  0/16     done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information:  0/16     done

+ mkfs.xfs /dev/test_vggroup20230809021908/test_lv320230809022231
oe_test_FSIO_mount_empty_dir.sh: line 33: mkfs.xfs: command not found
+ ext3_point=/mnt/point120230809022231
+ ext4_point=/mnt/point220230809022231
+ xfs_point=/mnt/point320230809022231
+ mkdir /mnt/point120230809022231 /mnt/point220230809022231 /mnt/point320230809022231
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Wed Aug  9 02:22:38 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed Aug  9 02:22:39 2023 - INFO  - Start to run test.
+ mount /dev/test_vggroup20230809021908/test_lv120230809022231 /mnt/point120230809022231
+ CHECK_RESULT 0 0 0 'mount ext3 on empty directory failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='mount ext3 on empty directory failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mount /dev/test_vggroup20230809021908/test_lv220230809022231 /mnt/point220230809022231
+ CHECK_RESULT 0 0 0 'mount ext4 on empty directory failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='mount ext4 on empty directory failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mount /dev/test_vggroup20230809021908/test_lv320230809022231 /mnt/point320230809022231
mount: /mnt/point320230809022231: wrong fs type, bad option, bad superblock on /dev/mapper/test_vggroup20230809021908-test_lv320230809022231, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
+ CHECK_RESULT 32 0 0 'mount xfs on empty directory failed.'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='mount xfs on empty directory failed.'
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'mount xfs on empty directory failed.'
+ LOG_ERROR 'mount xfs on empty directory failed.'
+ message='mount xfs on empty directory failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'mount xfs on empty directory failed.'
Wed Aug  9 02:22:41 2023 - ERROR - mount xfs on empty directory failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_empty_dir.sh line 48'
+ message='oe_test_FSIO_mount_empty_dir.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_empty_dir.sh line 48'
Wed Aug  9 02:22:42 2023 - ERROR - oe_test_FSIO_mount_empty_dir.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed Aug  9 02:22:43 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Aug  9 02:22:44 2023 - ERROR - failed to execute the case.
+ exit 1
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Aug  9 02:22:45 2023 - INFO  - Start to restore the test environment.
+ REMOVE_FS /mnt/point120230809022231
+ point_list=($1)
++ seq 0 0
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/mnt/point120230809022231
++ df -T
++ grep /mnt/point120230809022231
++ awk '{print $1}'
+ lv=/dev/mapper/test_vggroup20230809021908-test_lv120230809022231
+ [[ /dev/mapper/test_vggroup20230809021908-test_lv120230809022231 == '' ]]
+ umount -f /mnt/point120230809022231
+ rm -rf /mnt/point120230809022231
+ DELETE_LV /dev/mapper/test_vggroup20230809021908-test_lv120230809022231
+ lvname=/dev/mapper/test_vggroup20230809021908-test_lv120230809022231
+ lvremove /dev/mapper/test_vggroup20230809021908-test_lv120230809022231 -y
  Logical volume "test_lv120230809022231" successfully removed.
+ REMOVE_FS /mnt/point220230809022231
+ point_list=($1)
++ seq 0 0
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/mnt/point220230809022231
++ df -T
++ grep /mnt/point220230809022231
++ awk '{print $1}'
+ lv=/dev/mapper/test_vggroup20230809021908-test_lv220230809022231
+ [[ /dev/mapper/test_vggroup20230809021908-test_lv220230809022231 == '' ]]
+ umount -f /mnt/point220230809022231
+ rm -rf /mnt/point220230809022231
+ DELETE_LV /dev/mapper/test_vggroup20230809021908-test_lv220230809022231
+ lvname=/dev/mapper/test_vggroup20230809021908-test_lv220230809022231
+ lvremove /dev/mapper/test_vggroup20230809021908-test_lv220230809022231 -y
  Logical volume "test_lv220230809022231" successfully removed.
+ REMOVE_FS /mnt/point320230809022231
+ point_list=($1)
++ seq 0 0
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/mnt/point320230809022231
++ df -T
++ grep /mnt/point320230809022231
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed Aug  9 02:22:48 2023 - INFO  - End to restore the test environment.
