+ source ../common/storage_disk_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Wed Sep 27 14:20:23 2023 - INFO  - Start environment preparation.
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks='fd0 sr0 vdb'
+ disk_list=($disks)
+ local_disk=fd0
+ local_disk1=sr0
+ local_disk2=vdb
+ local_disk3=
+ pvcreate /dev/sr0 -y
oe_test_storage_lvm_set_limit.sh: line 23: pvcreate: command not found
+ vgcreate openeulertest /dev/sr0 -y
oe_test_storage_lvm_set_limit.sh: line 24: vgcreate: command not found
+ vgextend openeulertest /dev/fd0 -y
oe_test_storage_lvm_set_limit.sh: line 25: vgextend: command not found
+ vgextend openeulertest /dev/ -y
oe_test_storage_lvm_set_limit.sh: line 26: vgextend: command not found
+ vgextend openeulertest /dev/vdb -y
oe_test_storage_lvm_set_limit.sh: line 27: vgextend: command not found
+ LOG_INFO 'Environmental preparation is over.'
+ message='Environmental preparation is over.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Environmental preparation is over.'
Wed Sep 27 14:20:24 2023 - INFO  - Environmental preparation is over.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Wed Sep 27 14:20:24 2023 - INFO  - Start executing testcase!
+ expect -c '
    set timeout 30
    log_file testlog
    spawn lvcreate --type raid10 -i 2 -m 1 -L 50MB --maxrecoveryrate 128 -n test openeulertest
    expect "*\[y/n\]*" {send "y\r"}
    expect eof
'
spawn lvcreate --type raid10 -i 2 -m 1 -L 50MB --maxrecoveryrate 128 -n test openeulertest
couldn't execute "lvcreate": no such file or directory
    while executing
"spawn lvcreate --type raid10 -i 2 -m 1 -L 50MB --maxrecoveryrate 128 -n test openeulertest"
+ grep -iE 'fail|error' testlog
+ CHECK_RESULT 1 1
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ lvscan
oe_test_storage_lvm_set_limit.sh: line 42: lvscan: command not found
+ grep /dev/openeulertest/test
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_set_limit.sh line 43'
+ message='oe_test_storage_lvm_set_limit.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_set_limit.sh line 43'
Wed Sep 27 14:20:24 2023 - ERROR - oe_test_storage_lvm_set_limit.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of testcase execution!'
+ message='End of testcase execution!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution!'
Wed Sep 27 14:20:24 2023 - INFO  - End of testcase execution!
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Sep 27 14:20:24 2023 - ERROR - failed to execute the case.
+ exit 1
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Wed Sep 27 14:20:24 2023 - INFO  - start environment cleanup.
+ lvremove -y openeulertest/test
oe_test_storage_lvm_set_limit.sh: line 49: lvremove: command not found
+ vgremove -y openeulertest
oe_test_storage_lvm_set_limit.sh: line 50: vgremove: command not found
+ pvremove /dev/sr0 /dev/vdb /dev/fd0 /dev/
oe_test_storage_lvm_set_limit.sh: line 51: pvremove: command not found
+ rm -rf testlog
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Wed Sep 27 14:20:24 2023 - INFO  - Finish environment cleanup.
