+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Wed Oct 18 06:23:06 2023 - INFO  - Start to prepare the test environment.
+ useradd Jevons
useradd: user 'Jevons' already exists
++ id -u Jevons
+ uid=1001
+ LOG_INFO 'End to prepare the environment'
+ message='End to prepare the environment'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the environment'
Wed Oct 18 06:23:07 2023 - INFO  - End to prepare the environment
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed Oct 18 06:23:07 2023 - INFO  - Start to run test.
+ service auditd restart
Stopping logging: 
Redirecting start to /bin/systemctl start auditd.service
+ auditctl -D
No rules
+ CHECK_RESULT 0 0 0 'clean failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='clean failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ auditctl -a always,exit -S execve -F uid=1001 -k command
Error detecting machine type
+ CHECK_RESULT 255 0 0 'add rule failed'
+ actual_result=255
+ expect_result=0
+ mode=0
+ error_log='add rule failed'
+ exit_mode=0
+ '[' -z 255 ']'
+ '[' 0 -eq 0 ']'
+ test 255x '!=' 0x
+ test -n 'add rule failed'
+ LOG_ERROR 'add rule failed'
+ message='add rule failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'add rule failed'
Wed Oct 18 06:23:11 2023 - ERROR - add rule failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_monitor_do_command.sh line 35'
+ message='oe_test_audit_monitor_do_command.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_monitor_do_command.sh line 35'
Wed Oct 18 06:23:11 2023 - ERROR - oe_test_audit_monitor_do_command.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ auditctl -l
+ grep -e '-a always,exit -S execve -F uid=1001'
+ CHECK_RESULT 1 0 0 'grep failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='grep failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'grep failed'
+ LOG_ERROR 'grep failed'
+ message='grep failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'grep failed'
Wed Oct 18 06:23:12 2023 - ERROR - grep failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_monitor_do_command.sh line 37'
+ message='oe_test_audit_monitor_do_command.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_monitor_do_command.sh line 37'
Wed Oct 18 06:23:12 2023 - ERROR - oe_test_audit_monitor_do_command.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
++ date +%T
+ starttime=06:23:12
+ su - Jevons -c pwd
/home/Jevons
+ CHECK_RESULT 0 0 0 'login failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='login failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ date +%T
+ endtime=06:23:16
+ ausearch -ts 06:23:12 -te 06:23:16 -k command
+ grep pwd
Wed Oct 18 06:53:04 2023 - ERROR - Timeout : Command 'bash -x oe_test_audit_monitor_do_command.sh' timed out after 1799.9997732010006 seconds
