+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Sun Oct 22 14:46:13 2023 - INFO  - Start environmental preparation.
+ P_SSH_CMD --cmd 'cp /etc/chrony.conf /etc/chrony.conf_bak;sed -i '\''s/^pool/#pool/'\'' /etc/chrony.conf;sed -i '\''s/^#allow.*/allow all/'\'' /etc/chrony.conf;sed -i '\''s/^#local.*/local/'\'' /etc/chrony.conf;systemctl restart chronyd.service;systemctl stop firewalld.service' --node 2
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --cmd 'cp /etc/chrony.conf /etc/chrony.conf_bak;sed -i '\''s/^pool/#pool/'\'' /etc/chrony.conf;sed -i '\''s/^#allow.*/allow all/'\'' /etc/chrony.conf;sed -i '\''s/^#local.*/local/'\'' /etc/chrony.conf;systemctl restart chronyd.service;systemctl stop firewalld.service' --node 2
Sun Oct 22 14:46:19 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ cp /etc/chrony.conf /etc/chrony.conf_bak
+ sed -i 's/^pool.*/server  iburst minpoll 3 maxpoll 3/' /etc/chrony.conf
+ sed -i 's/^#allow.*/allow all/' /etc/chrony.conf
+ sed -i 's/^#local/local/' /etc/chrony.conf
+ systemctl restart chronyd.service
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Sun Oct 22 14:46:24 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Sun Oct 22 14:46:26 2023 - INFO  - Start testing...
+ test_execution chrony-wait.service
+ service=chrony-wait.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-10-22 14:46:26'
+ test_restart chrony-wait.service
+ service=chrony-wait.service
+ systemctl restart chrony-wait.service
Job for chrony-wait.service failed because a timeout was exceeded.
See "systemctl status chrony-wait.service" and "journalctl -xeu chrony-wait.service" for details.
+ CHECK_RESULT 1 0 0 'chrony-wait.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='chrony-wait.service restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'chrony-wait.service restart failed'
+ LOG_ERROR 'chrony-wait.service restart failed'
+ message='chrony-wait.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'chrony-wait.service restart failed'
Sun Oct 22 14:49:29 2023 - ERROR - chrony-wait.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Sun Oct 22 14:49:30 2023 - ERROR - ../common/common_lib.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status chrony-wait.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'chrony-wait.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='chrony-wait.service restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'chrony-wait.service restart failed'
+ LOG_ERROR 'chrony-wait.service restart failed'
+ message='chrony-wait.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'chrony-wait.service restart failed'
Sun Oct 22 14:49:40 2023 - ERROR - chrony-wait.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Sun Oct 22 14:49:42 2023 - ERROR - ../common/common_lib.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl stop chrony-wait.service
+ CHECK_RESULT 0 0 0 'chrony-wait.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='chrony-wait.service stop failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status chrony-wait.service
+ grep 'Active: inactive'
+ CHECK_RESULT 1 0 0 'chrony-wait.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='chrony-wait.service stop failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'chrony-wait.service stop failed'
+ LOG_ERROR 'chrony-wait.service stop failed'
+ message='chrony-wait.service stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'chrony-wait.service stop failed'
Sun Oct 22 14:49:52 2023 - ERROR - chrony-wait.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Sun Oct 22 14:49:54 2023 - ERROR - ../common/common_lib.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start chrony-wait.service
Job for chrony-wait.service failed because a timeout was exceeded.
See "systemctl status chrony-wait.service" and "journalctl -xeu chrony-wait.service" for details.
+ CHECK_RESULT 1 0 0 'chrony-wait.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='chrony-wait.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'chrony-wait.service start failed'
+ LOG_ERROR 'chrony-wait.service start failed'
+ message='chrony-wait.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'chrony-wait.service start failed'
Sun Oct 22 14:52:56 2023 - ERROR - chrony-wait.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Sun Oct 22 14:52:58 2023 - ERROR - ../common/common_lib.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status chrony-wait.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'chrony-wait.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='chrony-wait.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'chrony-wait.service start failed'
+ LOG_ERROR 'chrony-wait.service start failed'
+ message='chrony-wait.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'chrony-wait.service start failed'
Sun Oct 22 14:53:08 2023 - ERROR - chrony-wait.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Sun Oct 22 14:53:09 2023 - ERROR - ../common/common_lib.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ test_enabled chrony-wait.service
+ service=chrony-wait.service
++ systemctl is-enabled chrony-wait.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ systemctl enable chrony-wait.service
++ grep 'Created symlink'
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/chrony-wait.service
+ find /etc/systemd/system/multi-user.target.wants/chrony-wait.service
/etc/systemd/system/multi-user.target.wants/chrony-wait.service
+ CHECK_RESULT 0 0 0 'chrony-wait.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='chrony-wait.service enable failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable chrony-wait.service
Removed "/etc/systemd/system/multi-user.target.wants/chrony-wait.service".
+ find /etc/systemd/system/multi-user.target.wants/chrony-wait.service
find: ‘/etc/systemd/system/multi-user.target.wants/chrony-wait.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'chrony-wait.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='chrony-wait.service disable failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2023-10-22 14:46:26' -u chrony-wait.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
Oct 22 14:49:27 openeuler systemd[1]: chrony-wait.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 14:49:27 openeuler systemd[1]: chrony-wait.service: Failed with result 'timeout'.
Oct 22 14:49:27 openeuler systemd[1]: Failed to start Wait for chrony to synchronize system clock.
Oct 22 14:52:54 openeuler systemd[1]: chrony-wait.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 14:52:54 openeuler systemd[1]: chrony-wait.service: Failed with result 'timeout'.
Oct 22 14:52:54 openeuler systemd[1]: Failed to start Wait for chrony to synchronize system clock.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of chrony-wait.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of chrony-wait.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of chrony-wait.service'
+ LOG_ERROR 'There is an error message for the log of chrony-wait.service'
+ message='There is an error message for the log of chrony-wait.service'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of chrony-wait.service'
Sun Oct 22 14:53:28 2023 - ERROR - There is an error message for the log of chrony-wait.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Sun Oct 22 14:53:30 2023 - ERROR - ../common/common_lib.sh line 28
+ '[' 0 -eq 1 ']'
+ return 0
+ test_reload chrony-wait.service
+ service=chrony-wait.service
+ systemctl start chrony-wait.service
Job for chrony-wait.service failed because a timeout was exceeded.
See "systemctl status chrony-wait.service" and "journalctl -xeu chrony-wait.service" for details.
+ systemctl reload chrony-wait.service
+ grep 'Job type reload is not applicable'
Failed to reload chrony-wait.service: Job type reload is not applicable for unit chrony-wait.service.
+ CHECK_RESULT 0 0 0 'Job type reload is not applicable for unit chrony-wait.service'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit chrony-wait.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl status chrony-wait.service
+ grep 'Active: active'
+ systemctl status chrony-wait.service
+ grep 'inactive (dead)'
+ return 1
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Sun Oct 22 14:56:34 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 6
+ test 6 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sun Oct 22 14:56:36 2023 - ERROR - failed to execute the case.
+ exit 6
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Sun Oct 22 14:56:38 2023 - INFO  - start environment cleanup.
+ systemctl stop chrony-wait.service
+ cp -f /etc/chrony.conf_bak /etc/chrony.conf
+ systemctl restart chronyd.service
+ P_SSH_CMD --cmd '\cp -f /etc/chrony.conf_bak /etc/chrony.conf;systemctl restart chronyd.service;systemctl start firewalld.service' --node 2
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --cmd '\cp -f /etc/chrony.conf_bak /etc/chrony.conf;systemctl restart chronyd.service;systemctl start firewalld.service' --node 2
Sun Oct 22 14:56:48 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Sun Oct 22 14:56:50 2023 - INFO  - Finish environment cleanup!
