+ source ./common/disk_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment!'
+ message='Start to prepare the test environment!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment!'
Fri Sep 22 00:21:25 2023 - INFO  - Start to prepare the test environment!
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks='vdb vdc'
+ disk_list=($disks)
+ local_disk=vdb
+ local_disk1=vdc
+ local_disk2=
+ local_disk3=
+ DNF_INSTALL fio
+ pkgs=fio
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs fio --node 1 --tempfile ''
Fri Sep 22 00:23:20 2023 - INFO  - pkgs:(fio) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ echo dsafdsfdddddddddddddddddddddddddddddddddddddddddd
+ LOG_INFO 'End to prepare the test environment!'
+ message='End to prepare the test environment!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment!'
Fri Sep 22 00:23:24 2023 - INFO  - End to prepare the test environment!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Fri Sep 22 00:23:27 2023 - INFO  - Start executing testcase!
+ fio-genzipf -t normal
+ grep 'Generating Normal distribution with 0.000000'
+ CHECK_RESULT 1 0 0 'failed to test fio-genzipf-t option'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='failed to test fio-genzipf-t option'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'failed to test fio-genzipf-t option'
+ LOG_ERROR 'failed to test fio-genzipf-t option'
+ message='failed to test fio-genzipf-t option'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to test fio-genzipf-t option'
Fri Sep 22 00:23:56 2023 - ERROR - failed to test fio-genzipf-t option
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_004.sh line 31'
+ message='oe_test_fio_004.sh line 31'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_004.sh line 31'
Fri Sep 22 00:23:59 2023 - ERROR - oe_test_fio_004.sh line 31
+ '[' 0 -eq 1 ']'
+ return 0
+ grep Total
+ fio-genzipf -i zipf theta
+ CHECK_RESULT 1 0 0 'failed to test fio-genzipf-i option'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='failed to test fio-genzipf-i option'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'failed to test fio-genzipf-i option'
+ LOG_ERROR 'failed to test fio-genzipf-i option'
+ message='failed to test fio-genzipf-i option'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to test fio-genzipf-i option'
Fri Sep 22 00:24:28 2023 - ERROR - failed to test fio-genzipf-i option
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_004.sh line 33'
+ message='oe_test_fio_004.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_004.sh line 33'
Fri Sep 22 00:24:30 2023 - ERROR - oe_test_fio_004.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ fio-genzipf -i zipf theta -o 2
+ grep Rows
+ CHECK_RESULT 1 0 0 'fio-genzipf -o option failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='fio-genzipf -o option failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'fio-genzipf -o option failed'
+ LOG_ERROR 'fio-genzipf -o option failed'
+ message='fio-genzipf -o option failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'fio-genzipf -o option failed'
Fri Sep 22 00:24:56 2023 - ERROR - fio-genzipf -o option failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_004.sh line 35'
+ message='oe_test_fio_004.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_004.sh line 35'
Fri Sep 22 00:24:59 2023 - ERROR - oe_test_fio_004.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ fio-genzipf -i zipf theta -o 2 -c
+ grep 1
+ CHECK_RESULT 1 0 0 'fio-genzipf -i zipf theta option failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='fio-genzipf -i zipf theta option failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'fio-genzipf -i zipf theta option failed'
+ LOG_ERROR 'fio-genzipf -i zipf theta option failed'
+ message='fio-genzipf -i zipf theta option failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'fio-genzipf -i zipf theta option failed'
Fri Sep 22 00:25:29 2023 - ERROR - fio-genzipf -i zipf theta option failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_004.sh line 37'
+ message='oe_test_fio_004.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_004.sh line 37'
Fri Sep 22 00:25:33 2023 - ERROR - oe_test_fio_004.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'Generating Zipf distribution'
+ fio-genzipf -g 2
Generating Zipf distribution with 1.200000 input and 2 GiB size and 4096 block_size.
+ CHECK_RESULT 0 0 0 'fio-genzipf -g 2 option failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='fio-genzipf -g 2 option failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 'hits satisfied'
+ fio-genzipf -p 2
+ CHECK_RESULT 1 0 0 'fio-genzipf -p option failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='fio-genzipf -p option failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'fio-genzipf -p option failed'
+ LOG_ERROR 'fio-genzipf -p option failed'
+ message='fio-genzipf -p option failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'fio-genzipf -p option failed'
Fri Sep 22 00:26:12 2023 - ERROR - fio-genzipf -p option failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_004.sh line 41'
+ message='oe_test_fio_004.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_004.sh line 41'
Fri Sep 22 00:26:14 2023 - ERROR - oe_test_fio_004.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ fio-genzipf -b 40000
+ grep 'Generating Zipf distribution with'
Generating Zipf distribution with 1.200000 input and 500 GiB size and 40000 block_size.
+ CHECK_RESULT 0 0 0 'fio-genzipf -b option failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='fio-genzipf -b option failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep Version
+ fio-verify-state test.txt
Size mismatch
Version:	0x66617364
+ CHECK_RESULT 0 0 0 'fio-verify-state option failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='fio-verify-state option failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fio-dedupe -t 3 /dev/vdb
+ grep 'Will check </dev/vdb>'
Will check </dev/vdb>, size <2147483648>, using 3 threads
+ CHECK_RESULT 0 0 0 'check disk failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='check disk failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 'Will check </dev/vdb>'
+ fio-dedupe -d 3 /dev/vdb
Will check </dev/vdb>, size <2147483648>, using 4 threads
+ CHECK_RESULT 0 0 0 'check disk failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='check disk failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End of testcase execution!'
+ message='End of testcase execution!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution!'
Fri Sep 22 00:29:19 2023 - INFO  - End of testcase execution!
+ CASE_RESULT 0
+ case_re=0
+ test -z 5
+ test 5 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Sep 22 00:29:21 2023 - ERROR - failed to execute the case.
+ exit 5
+ post_test
+ LOG_INFO 'Start environment cleanup.'
+ message='Start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment cleanup.'
Fri Sep 22 00:29:24 2023 - INFO  - Start environment cleanup.
+ rm -rf test.txt
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Fri Sep 22 00:29:28 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Fri Sep 22 00:29:31 2023 - INFO  - Finish environment cleanup.
