+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 0 -eq 0 ]]
+++ lsblk
+++ grep test_vggroup
+++ head -n 1
+++ awk '{print $1}'
+++ cut -d - -f 1
++ vggroup=└─test_vggroup20231018040600
++ vggroup=test_vggroup20231018040600
++ vgremove test_vggroup20231018040600 -y
  Logical volume "test_lv20231018040600" successfully removed.
  Volume group "test_vggroup20231018040600" successfully removed
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Wed Oct 18 04:06:16 2023 - INFO  - Start to prepare the database config.
++ date +%Y%m%d%H%M%S
+ cur_date=20231018040616
++ CREATE_VG
+++ date +%Y%m%d%H%M%S
++ cur_date=20231018040616
+++ grep disk
+++ lsblk
+++ awk '{print $1}'
+++ tail -n 1
++ free_disk=vdb
++ disk_name=/dev/vdb
++ pvcreate /dev/vdb -f
++ [[ 0 -eq 0 ]]
++ vggroup=test_vggroup20231018040616
++ vgcreate test_vggroup20231018040616 /dev/vdb
++ printf test_vggroup20231018040616
+ vggroup=test_vggroup20231018040616
+ lv=test_lv20231018040616
+ lvcreate -n test_lv20231018040616 -L 2G test_vggroup20231018040616 -y
+ mkfs.ext3 /dev/test_vggroup20231018040616/test_lv20231018040616
mke2fs 1.47.0 (5-Feb-2023)
Discarding device blocks:      0/524288             done                            
Creating filesystem with 524288 4k blocks and 131072 inodes
Filesystem UUID: fd200768-00a6-47e1-9ea8-9c881fee9bb6
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912

Allocating group tables:  0/16     done                            
Writing inode tables:  0/16     done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information:  0/16     done

+ ext3_point=/mnt/test20231018040616
+ mkdir /mnt/test20231018040616
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Wed Oct 18 04:06:19 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed Oct 18 04:06:20 2023 - INFO  - Start to run test.
+ mount -t ext3 -o sync /dev/test_vggroup20231018040616/test_lv20231018040616 /mnt/test20231018040616
+ CHECK_RESULT 0 0 0 'Mount ext3 by sync failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Mount ext3 by sync failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ dd if=/dev/zero of=/mnt/test20231018040616/testFile bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 34.0626 s, 31.5 MB/s
+ CHECK_RESULT 0 0 0 'Write file failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Write file failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount -f /dev/test_vggroup20231018040616/test_lv20231018040616
+ CHECK_RESULT 0 0 0 'Umount failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Umount failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed Oct 18 04:06:57 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Wed Oct 18 04:06:58 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Oct 18 04:06:58 2023 - INFO  - Start to restore the test environment.
+ rm -rf /mnt/test20231018040616
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed Oct 18 04:06:59 2023 - INFO  - End to restore the test environment.
